next: null
# Format: <chance>:<command>. You may use <player> to replace it with the name of the player clicking the chest.
commands:
  - '3:crate give to <player> stratospheric 1'
  - '2:crate give to <player> mesospheric 1'
  - '1:crate give to <player> exospheric 1'
  - '5:eco give <player> 5000'
  - '5:eco give <player> 10000'
  - '5:eco give <player> 20000'
  - '5:eco give <player> 40000'
  - '4:give <player> emerald_block 10'
  - '4:give <player> diamond_block 10'
  - '4:give <player> gold_block 10'
  - '4:give <player> iron_block 10'