name: MomentoPerIslandEnvoys
version: '${project.version}'
main: ca.dannyferguson.momentoperislandenvoys.MomentoPerIslandEnvoys
api-version: 1.16
depend: [SuperiorSkyblock2, PlaceholderAPI]
commands:
  testenvoy:
  envoy:
